# Generated by Django 3.2.5 on 2022-12-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
