# Generated by Django 3.2.5 on 2022-12-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_trade_trade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_date',
            field=models.DateField(null=True),
        ),
    ]
