# Generated by Django 3.2.5 on 2022-12-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_trade_trade_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_date',
        ),
    ]
